stages:
  - build
  - deploy

build: 
  stage: build
  image: node:9
  script: 
    - npm install
    - npm run build
  artifacts:
    paths:
    - dist/
    expire_in: 1 hrs

deploy:
  stage: deploy
  only:
    - master
  script:
    - apt-get update -qq && apt-get install -y -qq lftp
    - lftp --delete-first "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; mirror --delete-first -Rev dist/ ./public_html/  --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"